std::bad_exception *__fastcall sub_33D570(std::bad_exception *a1)
{
  std::bad_exception::~bad_exception(a1);
  sub_33AC04(a1);
  return a1;
}
